Add support for 1.20.1
Minecraft-Transit-Railway/Minecraft-Mappings pull request #5
Opened 2024-04-24 16:37 UTC by NoaHimesaka1873

Yes, I did it! It's my first time using Java so there will be some rough edges.

2024-04-24 17:54 UTC, NoaHimesaka1873 commented
I will work on the build issue in Friday.

2024-04-25 14:01 UTC, NoaHimesaka1873 commented
Had some time left so fixed it!

2024-04-29 03:44 UTC, Kenny-Hui requested changes

2024-04-29 03:44 UTC, Kenny-Hui commented on fabric/1.20.1-mapping/src/main/java/org/mtr/mapping/mapper/ClickableWidgetExtension.java
> +
Please override mouseScrolled2 and call mouseScroll3, the mapped mouseScrolled3 method would not get called otherwise (Fabric)

2024-04-29 03:44 UTC, Kenny-Hui commented on forge/1.20.1-mapping/src/main/java/org/mtr/mapping/mapper/ClickableWidgetExtension.java
> +	public boolean mouseScrolled3(double mouseX, double mouseY, double amount) {
Please override mouseScrolled2 and call mouseScroll3, the mapped mouseScrolled3 method would not get called otherwise (Forge)

2024-04-29 07:47 UTC, Kenny-Hui approved these changes

2024-04-29 18:26 UTC, merged